version: '3.7'

services:
  db:
    image: postgres:alpine

    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host

    volumes:
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d/

  db-client:
    image: postgres:alpine
    command: ["psql", "-h", "db", "-U", "green_app"]
