version: '3.7'

services:
  db:
    image: postgres:alpine

    ports:
      - target: 5432
        published: 1443
        protocol: tcp
        mode: host

    volumes:
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d/
